#!/bin/sh

# Modify the variable to fit your local make
MAKE=make

if ! command -v $MAKE 2>&1 1>/dev/null;
then
    echo "No Make on the system" >&2
    exit 1
fi

# Set your own custom variables here.
CGI_PROGRAM=

if ! [ -z "$CGI_PROGRAM" ];
then
    SET_CGI_PROGRAM="CGI_PROGRAM=${CGI_PROGRAM}"
fi

$MAKE clean $SET_CGI_PROGRAM